package ru.meridor.website.util

import java.io.File
import org.apache.commons.io.FileUtils

/**
 * Contains a set of methods to generate other classes using a string builder
 */
trait FileGenerationSupport {
  /**
   * Stores a single indent text
   */
  protected val INDENT: String = "  "

  /**
   * Stores indents count to be used
   */
  private var indentsCount: Int = 0

  /**
   * Stores text of the class currently being generated
   */
  private val classContents: StringBuilder = new StringBuilder

  /**
   * Increases indentation
   */
  protected def indent() {
    indentsCount += 1
  }

  /**
   * Decreases indentation
   */
  protected def outdent() {
    indentsCount -= 1
  }

  /**
   * Appends random text
   * @param s
   */
  protected def append(s: String) {
    classContents.append(s)
  }

  /**
   * Appends an empty line
   */
  protected def appendln() {
    appendln("")
  }

  /**
   * Appends a line with specified text
   * @param s
   */
  protected def appendln(s: String) {
    classContents.append(INDENT * indentsCount + s + "\n")
  }

  /**
   * Completely clears generator contents in order to generate a new file
   */
  protected def reset() {
    classContents.setLength(0)
    indentsCount = 0
  }

  /**
   * Generate comments that this class was generated automatically
   */
  protected def appendInfoHeader() {
    appendln("/***********************************************************")
    appendln(" * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *")
    appendln(" ***********************************************************/")
  }

  /**
   * Gets generated class contents
   * @return currentClass
   */
  protected def getClassContents: String = classContents.toString()

  /**
   * Outputs file contents
   * @param fileName
   * @throws java.io.IOException
   * @throws java.net.URISyntaxException
   */
  protected def writeToFile(outputDirectory: String, fileName: String) {
    val dir: File = new File(outputDirectory)
    dir.mkdirs
    FileUtils.writeStringToFile(new File(dir, fileName), getClassContents)
  }

}